In [1]:
import importlib

In [2]:


import pandas as pd
import data_loader
import user_profile as user_pf

In [3]:
# Change this to True if you are running on Google Colab
RUNNING_ON_COLAB = False

# Constants
USER_ID = 999999

In [4]:
if RUNNING_ON_COLAB:
    data_loader.mount_drive()

In [5]:
# Load the data
films_df = data_loader.load_movies()
ratings_df = data_loader.load_ratings()
credits_df = data_loader.load_credits()

/Users/Cathal/Rec-Genie/rec-sys/data_loader.py:15: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(dataset_path + "/movies_metadata.csv", usecols=['id', 'title', 'release_date', 'genres', 'popularity', 'vote_average', 'vote_count'])

In [6]:
print("Data dimensions:")
print("films_df: ", films_df.shape)
print("ratings_df: ", ratings_df.shape)
print("credits_df: ", credits_df.shape)

Data dimensions:
films_df:  (45466, 7)
ratings_df:  (32000204, 3)
credits_df:  (45476, 3)

In [7]:
credits_df.shape

(45476, 3)

In [8]:
films_df.columns

Index(['genres', 'id', 'popularity', 'release_date', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [9]:
# Find film_df entry 100 - Lock Stock and Two Smoking Barrels
films_df[films_df['id'] == 100]

Empty DataFrame
Columns: [genres, id, popularity, release_date, title, vote_average, vote_count]
Index: []

In [10]:
# Drop the weird film entry
films_df = films_df.drop(35587)

In [11]:
import preprocessing as pre

In [12]:
# Data preprocessing
# One-hot encode the genres
ohe_films_df, genre_list_mlb = pre.one_hot_encode_genres(films_df)

In [13]:
ohe_films_df.columns

Index(['id', 'popularity', 'release_date', 'title', 'vote_average',
       'vote_count', 'Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History',
       'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie',
       'Thriller', 'War', 'Western'],
      dtype='object')

In [14]:
# Gather info on directors and cast
credits_df = pre.condense_credits(credits_df)

In [15]:
print(type(ohe_films_df), type(credits_df))  # Debugging line

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'>

In [16]:

# Tidy the noise and merge the credits' metadata with the films DataFrame
films_df = pre.data_tidying(ohe_films_df, credits_df)
print(films_df.columns)

Index(['id', 'popularity', 'release_date', 'title', 'vote_average',
       'vote_count', 'Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History',
       'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie',
       'Thriller', 'War', 'Western', 'cast_info', 'director_info'],
      dtype='object')

In [17]:
# Generate the user profile
user_ratings_df = user_pf.load_user_ratings()
user_profile = user_pf.create_user_profile(USER_ID, films_df, user_ratings_df, genre_list_mlb)

In [18]:
# Append the user profile to the ratings DataFrame
ratings_df = pd.concat([ratings_df, user_ratings_df], ignore_index=True)

In [19]:
import hybrid_recommender as hyb
importlib.reload(hyb)

In [20]:

# Generate recommendations
recommendations = hyb.hybrid_recommend(999999, user_profile, films_df, credits_df, ratings_df, genre_list_mlb)

Numba is using threading layer workqueue - consider TBB
found 1 potential runtime problems - see https://boi.st/lkpy-perf

User-User algorithm set up!

In [21]:
len(recommendations)

400

In [22]:
score_breakdown = hyb.score_breakdown(films_df, recommendations)

In [23]:
score_breakdown.head(50)sadsa

,id,title,release_date,vote_average,vote_count,score,cast_score,director_score,genre_score,user_user_score
5252,1894,Star Wars: Episode II - Attack of the Clones,2002-05-15,6.4,4074.0,10.323623,7.98,0.00,5.8320,3.104663
10138,272,Batman Begins,2005-06-10,7.5,7511.0,9.252858,5.40,0.00,7.5820,3.349898
11104,1164,Babel,2006-09-08,6.9,1083.0,8.733337,3.21,0.00,10.1580,3.642097
1310,2212,Nightwatch,1997-01-31,6.2,104.0,8.596010,4.74,0.00,4.9164,3.901418
12331,4787,Cassandra's Dream,2007-06-18,6.1,219.0,8.584150,4.74,0.00,6.6820,3.395190
10584,1420,Breakfast on Pluto,2005-09-03,7.0,77.0,8.547969,4.08,0.00,7.2870,3.651609
12615,8681,Taken,2008-02-18,7.2,4444.0,8.470072,4.08,0.00,6.6540,3.750952
278,1945,Nell,1994-12-23,6.1,128.0,8.344134,4.08,0.00,7.7310,3.323454
9557,2567,The Aviator,2004-12-17,7.0,1526.0,8.335127,3.63,0.00,10.1580,2.949887
4186,824,Moulin Rouge!,2001-03-09,7.4,1348.0,8.324154,4.74,0.00,3.4580,4.037914
7005,587,Big Fish,2003-12-25,7.6,2064.0,8.291363,4.74,0.00,5.8100,3.346563
2988,293,A River Runs Through It,1992-10-09,7.0,241.0,8.226031,2.01,0.00,10.1580,3.974791
2220,73,American History X,1998-10-30,8.2,3120.0,8.177890,2.25,0.00,10.1580,3.758650
5353,8665,K-19: The Widowmaker,2002-07-19,6.1,273.0,8.106396,4.08,0.00,6.0100,3.567596
6685,26850,Under Suspicion,1991-09-27,6.1,15.0,8.079097,4.08,0.00,6.6820,3.352137
12246,8272,The Savages,2007-01-19,6.8,112.0,8.075827,2.16,0.00,10.1580,3.719587
7286,237,Young Adam,2003-09-26,5.9,46.0,8.054987,4.74,0.00,5.0835,3.313607
19469,179251,We Live Again,1934-11-01,0.0,0.0,8.052582,0.00,0.00,10.1580,5.208342
10237,1635,The Island,2005-07-20,6.5,1813.0,8.050990,4.74,0.00,5.7000,3.136990
46,807,Se7en,1995-09-22,8.1,5915.0,8.005194,2.91,1.68,3.5800,3.789794
289,101,Leon: The Professional,1994-09-14,8.2,4293.0,7.936547,3.42,0.00,6.6820,3.671587
28275,86835,Knight of Cups,2015-02-08,5.7,198.0,7.843977,4.71,0.00,5.2230,3.084537
8256,866,Finding Neverland,2004-10-17,7.2,1269.0,7.830894,1.98,-0.08,10.1580,3.656654
10387,8202,Æon Flux,2005-11-30,5.4,717.0,7.827852,3.69,0.00,5.9460,3.579972
22966,79073,Messages Deleted,2009-02-05,4.8,14.0,7.783107,0.00,4.88,2.1400,3.767907
37998,158928,The Roman Spring of Mrs. Stone,2003-05-04,4.5,4.0,7.721182,0.00,0.00,10.1580,4.876942
18815,57165,Wrath of the Titans,2012-03-27,5.5,1459.0,7.680120,8.73,0.00,5.6040,0.000000
21027,137182,The Broken Circle Breakdown,2012-10-09,7.7,341.0,7.663027,0.00,0.00,10.1580,4.818787
1768,4415,Les Misérables,1998-05-01,7.1,157.0,7.644928,4.08,0.00,4.3995,3.557068
5861,640,Catch Me If You Can,2002-12-25,7.7,3917.0,7.632322,3.60,0.00,7.3710,3.048442
12205,4515,Lions for Lambs,2007-10-22,6.0,223.0,7.602638,1.41,1.60,6.5835,3.652258
13719,534,Terminator Salvation,2009-05-20,5.9,2496.0,7.589357,3.15,0.00,5.7320,3.779397
15035,18823,Clash of the Titans,2010-04-01,5.6,2280.0,7.536760,8.73,0.00,5.0920,0.000000
8267,2288,Closer,2004-12-01,6.7,845.0,7.535262,3.36,0.00,5.2230,3.720822
10120,787,Mr. & Mrs. Smith,2005-06-07,6.5,3048.0,7.531386,2.94,0.00,6.9705,3.521646
8270,163,Ocean's Twelve,2004-12-09,6.4,2169.0,7.528200,3.42,0.00,4.9440,3.749880
25503,172391,Khumba,2013-07-18,5.8,74.0,7.512357,4.08,0.00,2.9240,3.837637
31058,279988,Extinction: Nature Has Evolved,2017-03-10,0.0,10.0,7.499593,0.00,3.40,5.4540,3.592473
28324,37058,I'm Here,2010-03-01,7.4,53.0,7.471589,0.93,0.00,10.1580,3.976349
34752,164041,The Seventh Companion,1968-04-14,7.7,3.0,7.395276,0.00,0.00,10.1580,4.551036
15535,26350,Perestroika,2009-03-20,3.0,2.0,7.391811,1.38,0.00,10.1580,3.581571
2522,8785,The Saragossa Manuscript,1965-02-09,7.4,23.0,7.368372,0.00,2.92,4.2735,4.127792
26674,178607,Right Cross,1950-10-06,0.0,0.0,7.366503,0.00,1.60,10.1580,3.402263
44713,27221,Where the Green Ants Dream,1984-08-31,7.1,10.0,7.345227,0.00,0.00,10.1580,4.500987
9313,2191,Stranded,2001-09-23,5.8,14.0,7.331318,0.00,3.40,6.4500,3.145318
38789,197849,Winter Wind,1969-12-04,10.0,1.0,7.308398,0.00,0.00,10.1580,4.464158
35762,174751,Jane Got a Gun,2016-01-01,5.4,293.0,7.302120,8.01,0.00,6.0540,0.000000
13033,4960,"Synecdoche, New York",2008-10-24,7.4,286.0,7.301128,2.16,0.00,10.1580,2.944888
10852,7483,Free Zone,2005-04-18,4.8,16.0,7.272625,2.19,0.00,10.1580,2.895385
13266,4148,Revolutionary Road,2008-12-19,6.8,824.0,7.265194,3.33,0.00,5.2230,3.471754

In [24]:
# weights = {
#     'cast_ft_weight': 0.3,
#     'director_ft_weight': 0.3,
#     'genre_ft_weight': 0.15,
#     'user_user_weight': 1,
#     'content_weight': 0.7,
#     'collab_weight': 0.3
# }