In [82]:
import importlib

In [83]:


import pandas as pd
import data_loader
import user_profile as user_pf

In [84]:
# Change this to True if you are running on Google Colab
RUNNING_ON_COLAB = False

# Constants
USER_ID = 999999

In [85]:
if RUNNING_ON_COLAB:
    data_loader.mount_drive()

In [86]:

films_df = data_loader.load_movies()

In [87]:
# Load the data
# films_df = data_loader.load_movies()
ratings_df = data_loader.load_ratings()
credits_df = data_loader.load_credits()

In [88]:
print("Data dimensions:")
print("films_df: ", films_df.shape)
print("ratings_df: ", ratings_df.shape)
print("credits_df: ", credits_df.shape)

Data dimensions:
films_df:  (1070323, 8)
ratings_df:  (32000204, 3)
credits_df:  (45476, 3)

In [89]:
credits_df.shape

(45476, 3)

In [90]:
films_df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'release_date', 'imdb_id',
       'popularity', 'genres'],
      dtype='object')

In [91]:
# Find film_df entry 100 - Lock Stock and Two Smoking Barrels
films_df[films_df['id'] == 100]

,id,title,vote_average,vote_count,release_date,imdb_id,popularity,genres
65,100,"Lock, Stock and Two Smoking Barrels",8.115,6692.0,1998-08-28,tt0120735,1.946,"Comedy, Crime"

In [92]:
# Drop the weird film entry
films_df = films_df.drop(35587)

In [93]:
import preprocessing as pre
# importlib.reload(pre)

In [94]:
# Drop films before 1985 and after today
films_df = pre.filter_films(films_df)

In [114]:
films_df.shape

(28833, 28)

In [96]:
films_df.sort_values('release_date', ascending=False)

,id,title,vote_average,vote_count,release_date,imdb_id,popularity,genres
304132,447273,Snow White,2.5,22.0,2025-03-19,tt6208148,24.058,"Family, Fantasy"
939885,1297763,Batman Ninja vs. Yakuza League,5.7,22.0,2025-03-17,tt32508210,18.282,"Animation, Action"
1059269,1438267,Gamad Machmad 4,4.4,8.0,2025-03-16,NaN,10.171,"Drama, Comedy, Thriller, Action"
930641,1286773,The Metropolitan Opera: Fidelio,7.4,7.0,2025-03-15,NaN,11.995,Music
1042445,1417677,Bill Burr: Drop Dead Years,7.9,15.0,2025-03-14,tt34686029,6.094,Comedy
...,...,...,...,...,...,...,...,...
141908,248595,Alien Outlaw,2.7,13.0,1985-01-01,tt0190229,3.308,"Mystery, Science Fiction, Comedy, Western, Horror"
59004,82942,'Master Harold'... and the Boys,6.2,6.0,1985-01-01,tt0089564,4.057,Drama
127434,220343,Anna Karenina,5.2,6.0,1985-01-01,tt0088726,4.618,"Drama, Romance, TV Movie"
98676,161426,You Killed Me First,4.8,19.0,1985-01-01,tt0190157,0.671,"Drama, Horror"
121546,208543,Majestic Thunderbolt,3.7,6.0,1985-01-01,tt0269505,0.212,"Crime, Action"

In [97]:
films_df.head()

,id,title,vote_average,vote_count,release_date,imdb_id,popularity,genres
0,2,Ariel,7.1,340.0,1988-10-21,tt0094675,9.400,"Comedy, Drama, Romance, Crime"
1,3,Shadows in Paradise,7.3,403.0,1986-10-17,tt0092149,7.088,"Comedy, Drama, Romance"
2,5,Four Rooms,5.9,2678.0,1995-12-09,tt0113101,3.547,"Comedy, Crime"
3,6,Judgment Night,6.5,333.0,1993-10-15,tt0107286,12.110,"Action, Crime, Thriller"
4,8,Life in Loops (A Megacities RMX),7.5,27.0,2006-01-01,tt0825671,3.203,Documentary

In [98]:
genres_films = films_df.copy()

In [99]:
# Data preprocessing
# # One-hot encode the genres
ohe_films_df, genre_list_mlb = pre.one_hot_encode_genres(genres_films)

In [100]:
ohe_films_df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'release_date', 'imdb_id',
       'popularity', 'Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror',
       'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie',
       'Thriller', 'War', 'Western'],
      dtype='object')

In [101]:
# Gather info on directors and cast
credits_df = pre.condense_credits(credits_df)

In [102]:
print(type(ohe_films_df), type(credits_df))  # Debugging line

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'>

In [103]:

# Tidy the noise and merge the credits' metadata with the films DataFrame
films_df = pre.data_tidying(ohe_films_df, credits_df)
# print(films_df.columns)

In [104]:
# Generate the user profile
user_ratings_df = user_pf.load_user_ratings()
user_profile = user_pf.create_user_profile(USER_ID, films_df, user_ratings_df, genre_list_mlb)

In [105]:
# Append the user profile to the ratings DataFrame
ratings_df = pd.concat([ratings_df, user_ratings_df], ignore_index=True)

In [106]:
# print all the values for vote_average in films_df
print((films_df['vote_count'] > 100).sum())

11368

In [107]:
films_df[films_df['vote_average'] != 0]

,id,title,vote_average,vote_count,release_date,imdb_id,popularity,Action,Adventure,Animation,...,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western,cast_info,director_info
0,2,Ariel,7.100,340.0,1988-10-21,tt0094675,9.400,0,0,0,...,0,0,1,0,0,0,0,0,"[(Turo Pajala, 54768), (Susanna Haavisto, 5476...","(Aki Kaurismäki, 2)"
1,3,Shadows in Paradise,7.300,403.0,1986-10-17,tt0092149,7.088,0,0,0,...,0,0,1,0,0,0,0,0,"[(Matti Pellonpää, 4826), (Kati Outinen, 5999)...","(Aki Kaurismäki, 3)"
2,5,Four Rooms,5.900,2678.0,1995-12-09,tt0113101,3.547,0,0,0,...,0,0,0,0,0,0,0,0,"[(Tim Roth, 3129), (Antonio Banderas, 3131), (...","(Allison Anders, 5)"
3,6,Judgment Night,6.500,333.0,1993-10-15,tt0107286,12.110,1,0,0,...,0,0,0,0,0,1,0,0,"[(Emilio Estevez, 2880), (Cuba Gooding Jr., 97...","(Stephen Hopkins, 6)"
4,12,Finding Nemo,7.800,19500.0,2003-05-30,tt0266543,8.524,0,0,1,...,0,0,0,0,0,0,0,0,"[(Albert Brooks, 13), (Ellen DeGeneres, 14), (...","(Andrew Stanton, 12)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28828,463800,Firebase,6.800,145.0,2017-06-28,tt7078926,6.090,1,0,0,...,0,0,0,1,0,0,1,0,"[(Steve Boyle, 190921), (Nic Rhind, 964251), (...","(Neill Blomkamp, 463800)"
28829,463906,The Saint,5.300,280.0,2017-07-11,tt2569088,9.959,1,1,0,...,0,0,0,0,0,0,0,0,"[(Adam Rayner, 144292), (Eliza Dushku, 13446),...","(Ernie Barbarash, 463906)"
28830,464111,Zygote,7.000,167.0,2017-07-12,tt7078780,7.634,0,0,0,...,0,0,0,1,0,0,0,0,"[(Dakota Fanning, 501), (Jose Pablo Cantillo, ...","(Neill Blomkamp, 464111)"
28831,464207,The Truth Is in the Stars,7.067,15.0,2017-05-01,tt7104950,3.632,0,0,0,...,0,0,0,0,0,0,0,0,"[(William Shatner, 1748), (Neil deGrasse Tyson...","(Craig Thompson, 464207)"
28832,468707,Thick Lashes of Lauri Mäntyvaara,5.500,16.0,2017-07-28,tt5742932,2.086,0,0,0,...,0,0,1,0,0,0,0,0,"[(Inka Haapamäki, 1860857), (Rosa Honkonen, 18...","(Hannaleena Hauru, 468707)"

In [125]:
import hybrid_recommender as hyb
importlib.reload(hyb)

In [126]:
# Generate recommendations
recommendations = hyb.hybrid_recommend(999999, user_profile, films_df, credits_df, ratings_df, genre_list_mlb)

User-User algorithm set up!
Rating before: 1.6435
Rating after: -0.35650000000000004
Rating before: 1.55
Rating after: -0.44999999999999996
Rating before: 1.95
Rating after: -0.050000000000000044
Rating before: 1.95
Rating after: -0.050000000000000044
Rating before: 1.95
Rating after: -0.050000000000000044
Rating before: 1.95
Rating after: -0.050000000000000044
Rating before: 1.9
Rating after: -0.10000000000000009
Rating before: 1.75
Rating after: -0.25
Rating before: 1.8
Rating after: -0.19999999999999996
Rating before: 1.65
Rating after: -0.3500000000000001
Rating before: 1.8
Rating after: -0.19999999999999996
Rating before: 1.66
Rating after: -0.3400000000000001
Rating before: 1.55
Rating after: -0.44999999999999996
Rating before: 1.75
Rating after: -0.25
Rating before: 1.75
Rating after: -0.25
Rating before: 1.95
Rating after: -0.050000000000000044
Rating before: 1.95
Rating after: -0.050000000000000044
Rating before: 1.8
Rating after: -0.19999999999999996
Rating before: 1.95
Rating after: -0.050000000000000044
Rating before: 1.9605
Rating after: -0.03950000000000009
Rating before: 1.1
Rating after: -0.8999999999999999
Rating before: 1.0555
Rating after: -0.9444999999999999
Rating before: 1.6
Rating after: -0.3999999999999999
Rating before: 1.6
Rating after: -0.3999999999999999
Rating before: 1.55
Rating after: -0.44999999999999996
Rating before: 1.864
Rating after: -0.1359999999999999
Rating before: 1.6
Rating after: -0.3999999999999999
Rating before: 1.85
Rating after: -0.1499999999999999
Rating before: 1.8
Rating after: -0.19999999999999996
Rating before: 1.6
Rating after: -0.3999999999999999
Rating before: 1.2
Rating after: -0.8
Rating before: 1.5
Rating after: -0.5
Rating before: 1.95
Rating after: -0.050000000000000044
Rating before: 1.9
Rating after: -0.10000000000000009
Rating before: 1.7
Rating after: -0.30000000000000004
Rating before: 1.85
Rating after: -0.1499999999999999
Rating before: 1.65
Rating after: -0.3500000000000001
Rating before: 1.5
Rating after: -0.5
Rating before: 1.85
Rating after: -0.1499999999999999
Rating before: 1.5
Rating after: -0.5
Rating before: 1.55
Rating after: -0.44999999999999996
Rating before: 1.55
Rating after: -0.44999999999999996
Rating before: 1.75
Rating after: -0.25
Rating before: 0.95
Rating after: -1.05
Rating before: 1.7
Rating after: -0.30000000000000004
Rating before: 1.75
Rating after: -0.25
Rating before: 1.7
Rating after: -0.30000000000000004
Rating before: 1.5
Rating after: -0.5
Rating before: 1.25
Rating after: -0.75
Rating before: 1.6
Rating after: -0.3999999999999999
Rating before: 1.75
Rating after: -0.25
Rating before: 1.35
Rating after: -0.6499999999999999
Rating before: 1.8595
Rating after: -0.14050000000000007

In [110]:
len(recommendations)

400

In [123]:
score_breakdown = hyb.score_breakdown(films_df, recommendations)

In [124]:
score_breakdown.head(50)

,id,title,release_date,vote_average,vote_count,score,cast_score,director_score,genre_score,user_user_score
143,272,Batman Begins,2005-06-10,7.700,21297.0,12.571658,5.40,4.88,7.4620,3.286298
775,1894,Star Wars: Episode II - Attack of the Clones,2002-05-15,6.600,13441.0,12.434603,7.98,2.92,5.9840,3.129083
569,1420,Breakfast on Pluto,2005-11-16,7.200,396.0,9.970016,4.08,2.00,7.4190,3.636696
1045,2567,The Aviator,2004-12-17,7.221,5405.0,9.663816,3.63,1.80,9.8580,3.102576
84,155,The Dark Knight,2008-07-16,8.519,33561.0,9.320366,1.32,4.88,6.3795,3.194106
1309,4538,The Darjeeling Limited,2007-09-07,7.200,3621.0,9.149036,1.41,3.72,6.9660,3.607556
490,1124,The Prestige,2006-10-17,8.202,16363.0,9.070780,1.32,4.88,4.7220,3.408620
986,2288,Closer,2004-12-03,6.800,3460.0,8.954535,3.36,1.56,4.9830,4.115295
340,640,Catch Me If You Can,2002-12-16,7.978,15936.0,8.849514,3.60,1.92,7.1910,2.972034
495,1164,Babel,2006-10-26,7.200,3782.0,8.734677,3.21,0.00,9.8580,3.727437
221,421,The Life Aquatic with Steve Zissou,2004-12-10,7.100,2922.0,8.719002,1.20,3.72,6.9660,3.324522
424,855,Black Hawk Down,2001-12-28,7.400,5856.0,8.561804,4.74,1.60,4.4960,2.864924
784,1907,The Beach,2000-02-03,6.486,4394.0,8.485789,2.43,3.40,4.7895,3.063729
1347,4787,Cassandra's Dream,2007-10-31,6.300,786.0,8.441350,4.74,0.00,5.8380,3.488710
414,824,Moulin Rouge!,2001-05-18,7.548,4571.0,8.303456,4.74,0.00,3.2980,4.062016
1928,8681,Taken,2008-02-18,7.395,11391.0,8.165392,4.08,0.00,5.5680,3.750352
804,1945,Nell,1994-12-23,6.600,513.0,8.163790,4.08,0.00,6.4950,3.489190
12029,44115,127 Hours,2010-11-12,7.100,7618.0,8.162702,0.81,3.40,6.3500,3.437702
309,587,Big Fish,2003-12-25,7.800,7300.0,8.089769,4.74,0.00,5.3020,3.287209
570,1422,The Departed,2006-10-04,8.159,15137.0,8.088874,2.43,1.80,5.8380,3.493234
31,73,American History X,1998-07-01,8.300,11751.0,8.065561,2.25,0.00,9.8580,3.730321
668,1635,The Island,2005-07-21,6.700,5436.0,8.047457,4.74,0.00,5.2710,3.253577
963,2212,Nightwatch,1997-01-31,6.000,396.0,7.993201,4.74,0.00,3.4185,3.718021
176,320,Insomnia,2002-05-24,6.944,4817.0,7.926557,0.00,4.88,4.4835,3.255177
130,237,Young Adam,2003-09-26,5.900,172.0,7.920977,4.74,0.00,4.4055,3.369437
314,597,Titanic,1997-11-18,7.905,25779.0,7.915760,3.33,1.20,4.9830,3.349520
49,101,Léon: The Professional,1994-09-14,8.300,15044.0,7.897953,3.42,0.00,7.4620,3.414593
1158,3131,Gangs of New York,2002-12-14,7.318,6727.0,7.864970,2.43,1.80,5.9180,3.246930
1366,4922,The Curious Case of Benjamin Button,2008-12-25,7.600,12965.0,7.741116,3.21,1.68,3.3180,3.389076
20268,137182,The Broken Circle Breakdown,2012-10-09,7.700,1057.0,7.690451,0.00,0.00,9.8580,4.930211
17803,86835,Knight of Cups,2015-09-10,5.700,660.0,7.686840,4.71,0.00,4.9830,2.994600
1800,8202,Æon Flux,2005-11-30,5.600,2256.0,7.584632,3.69,0.00,5.0080,3.599392
520,1272,Sunshine,2007-04-05,7.000,3868.0,7.512619,0.00,3.40,5.6260,3.557339
313,594,The Terminal,2004-06-17,7.300,8036.0,7.505771,1.17,1.92,7.4190,3.265451
1923,8665,K-19: The Widowmaker,2002-07-19,6.552,1047.0,7.493796,4.08,0.00,3.7788,3.579732
426,857,Saving Private Ryan,1998-07-24,8.200,16120.0,7.488703,1.17,1.92,5.1140,3.893783
16593,75981,La France,2007-09-21,6.400,16.0,7.479312,0.00,0.00,9.8580,4.719072
278,534,Terminator Salvation,2009-05-20,6.100,6552.0,7.462873,3.15,0.00,5.0080,3.855633
21422,172391,Khumba,2013-07-18,6.000,257.0,7.446921,4.08,0.00,3.0760,3.729641
8358,26350,Perestroika,2009-03-20,3.800,6.0,7.446356,1.38,0.00,9.8580,3.720116
1753,7979,The Kite Runner,2007-12-14,7.300,1151.0,7.434818,0.00,1.00,9.8580,3.974578
14388,57165,Wrath of the Titans,2012-03-28,5.700,4243.0,7.422520,8.73,0.00,4.6840,0.000000
6468,18823,Clash of the Titans,2010-03-26,5.900,6307.0,7.422520,8.73,0.00,4.6840,0.000000
1230,4148,Revolutionary Road,2008-12-19,6.986,3868.0,7.385568,3.33,0.00,4.9830,3.659328
392,787,Mr. & Mrs. Smith,2005-06-07,6.688,10524.0,7.342932,2.94,0.00,6.4935,3.466752
195,350,The Devil Wears Prada,2006-06-29,7.400,12209.0,7.334491,2.58,0.00,7.4190,3.451171
311,590,The Hours,2002-12-27,7.300,1750.0,7.331707,1.41,0.00,9.8580,3.584467
1933,8699,Anchorman: The Legend of Ron Burgundy,2004-06-28,6.700,4255.0,7.291323,0.00,1.76,4.9800,4.664923
1816,8272,The Savages,2007-11-28,6.800,380.0,7.282979,2.16,0.00,7.4190,3.693659
21539,174751,Jane Got a Gun,2015-12-31,5.800,809.0,7.274120,8.01,0.00,5.9540,0.000000

In [113]:
# weights = {
#     'cast_ft_weight': 0.3,
#     'director_ft_weight': 0.3,
#     'genre_ft_weight': 0.15,
#     'user_user_weight': 1,
#     'content_weight': 0.7,
#     'collab_weight': 0.3
# }